# Generated by Django 3.0.8 on 2020-12-13 05:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201212_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='current_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
