# Generated by Django 3.0.8 on 2020-12-14 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201213_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
